version: '3.8'

services:
  web:
    deploy:
      resources:
        limits:
          memory: "128M"
    restart: unless-stopped
    image: 'ghcr.io/kagchi/pengiriman-barang:latest-dev'
    env_file:
      - .env
    networks:
      internet:
        aliases:
          - web.internet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`pengiriman.kagchi.my.id`)"
      - "traefik.http.routers.web.entrypoints=web,websecure"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.tls.options=cloudflare@file"
      - "traefik.http.routers.web.middlewares=cloudflare-real-ip@file"
      - "traefik.http.services.web.loadbalancer.server.port=8000"

networks:
  internet:
    ipam:
      driver: default
      config:
        - subnet: 10.0.35.0/24
    internal: false