version: '3.8'

services:
  web:
    deploy:
      resources:
        limits:
          memory: "64M"
    restart: unless-stopped
    image: 'ghcr.io/kagchi/pengiriman-barang:latest-dev'
    env_file:
      - .env
    networks:
      internet:
        aliases:
          - web.internet
      compose_internet:
        aliases:
          - web.compose_internet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`pengiriman.kagchi.my.id`)"
      - "traefik.http.routers.web.entrypoints=web,websecure"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.tls.options=cloudflare@file"
      - "traefik.http.routers.web.middlewares=cloudflare-real-ip@file"
      - "traefik.http.services.web.loadbalancer.server.port=80"

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: "64M"
    env_file:
      - .env
    networks:
      internet:
        aliases:
          - phpmyadmin.internet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin-pengiriman.kagchi.my.id`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=web,websecure"
      - "traefik.http.routers.phpmyadmin.tls=true"
      - "traefik.http.routers.phpmyadmin.tls.options=cloudflare@file"
      - "traefik.http.routers.phpmyadmin.middlewares=cloudflare-real-ip@file"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
  
  maria_db:
    deploy:
      resources:
        limits:
          memory: "96M"
    restart: unless-stopped
    image: mariadb
    env_file:
      - .env
    networks:
      internet:
        aliases:
          - maria_db.internet
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:

networks:
  internet:
    ipam:
      driver: default
      config:
        - subnet: 10.0.35.0/24
    internal: false
  compose_internet:
    external: true